// Optimizes the uploaded Unsplash photos and generates the photo manifest.
//
// Reads source JPGs + credits from ../photos/, writes resized/compressed JPGs
// to ../public/photos/<id>.jpg, and emits ../src/sources/localPhotos.ts.
//
// Requires macOS `sips` (built in). Re-run after adding/removing photos:
//   node scripts/build-photos.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync, mkdirSync, statSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = join(ROOT, 'photos');
const OUT_DIR = join(ROOT, 'public', 'photos');
const MANIFEST = join(ROOT, 'src', 'sources', 'localPhotos.ts');
const MAX_DIM = 1600;
const QUALITY = 80;

rmSync(OUT_DIR, { recursive: true, force: true }); // avoid stale outputs
mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SRC_DIR).filter((f) => f.toLowerCase().endsWith('.jpg'));
const lines = readFileSync(join(SRC_DIR, 'photos.txt'), 'utf8')
  .split('\n')
  .map((l) => l.trim())
  .filter(Boolean);

const CREDIT = /Photo by <a href="([^"]+)">([^<]+)<\/a> on <a href="([^"]+)">Unsplash<\/a>/;

const photos = [];
for (const line of lines) {
  const m = line.match(CREDIT);
  if (!m) {
    console.warn('skip (unparsed credit):', line.slice(0, 60));
    continue;
  }
  const [, creatorUrl, creator, unsplashUrl] = m;
  const slug = new URL(unsplashUrl).pathname.split('/').pop() ?? '';
  // Unsplash photo IDs are the last 11 chars of the slug (they can contain '-').
  const id = slug.slice(-11);
  const alt = slug.slice(0, -12).replace(/-/g, ' ').trim();
  const srcFile = files.find((f) => f.includes(id));
  if (!srcFile) {
    console.warn('no source file for id', id, `(${creator})`);
    continue;
  }
  const outName = `${id}.jpg`;
  execFileSync('sips', [
    '-s', 'format', 'jpeg',
    '-s', 'formatOptions', String(QUALITY),
    '-Z', String(MAX_DIM),
    join(SRC_DIR, srcFile),
    '--out', join(OUT_DIR, outName),
  ], { stdio: 'ignore' });
  const kb = Math.round(statSync(join(OUT_DIR, outName)).size / 1024);
  console.log(`${outName.padEnd(20)} ${String(kb).padStart(4)} KB  ${creator}`);
  photos.push({ id, src: `/photos/${outName}`, creator, creatorUrl, unsplashUrl, alt });
}

const header = `// AUTO-GENERATED by scripts/build-photos.mjs — do not edit by hand.
// Unsplash photos, optimized and bundled. Re-run the script to regenerate.

export interface Photo {
  id: string;
  src: string;
  creator: string;
  creatorUrl: string;
  unsplashUrl: string;
  alt: string;
}

export const LOCAL_PHOTOS: Photo[] = ${JSON.stringify(photos, null, 2)};
`;
writeFileSync(MANIFEST, header);
console.log(`\nWrote ${photos.length} photos to ${OUT_DIR}`);
console.log(`Wrote manifest ${MANIFEST}`);
