// AUTO-GENERATED by scripts/build-photos.mjs — do not edit by hand.
// Unsplash photos, optimized and bundled. Re-run the script to regenerate.

export interface Photo {
  id: string;
  src: string;
  creator: string;
  creatorUrl: string;
  unsplashUrl: string;
  alt: string;
}

export const LOCAL_PHOTOS: Photo[] = [
  {
    "id": "EmaNvKiiOu0",
    "src": "/photos/EmaNvKiiOu0.jpg",
    "creator": "Yousef Salhamoud",
    "creatorUrl": "https://unsplash.com/@salhamoud?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/a-single-palm-tree-stands-against-a-clear-blue-sky-EmaNvKiiOu0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "a single palm tree stands against a clear blue sky"
  },
  {
    "id": "yMpykIcP_BY",
    "src": "/photos/yMpykIcP_BY.jpg",
    "creator": "Karsten Winegeart",
    "creatorUrl": "https://unsplash.com/@_karsten?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/french-bulldog-swimming-in-mccall-lake-yMpykIcP_BY?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "french bulldog swimming in mccall lake"
  },
  {
    "id": "SnO1rIPNAaA",
    "src": "/photos/SnO1rIPNAaA.jpg",
    "creator": "SLNC",
    "creatorUrl": "https://unsplash.com/@riverse?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/a-beautiful-lionfish-with-striped-fins-swimming-in-dark-water-SnO1rIPNAaA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "a beautiful lionfish with striped fins swimming in dark water"
  },
  {
    "id": "4Igpa3xYpnc",
    "src": "/photos/4Igpa3xYpnc.jpg",
    "creator": "Vitalii Khodzinskyi",
    "creatorUrl": "https://unsplash.com/@khodzinskyi?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/beach-soccer-goal-behind-fence-by-the-sea-4Igpa3xYpnc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "beach soccer goal behind fence by the sea"
  },
  {
    "id": "ADLkT2JF57c",
    "src": "/photos/ADLkT2JF57c.jpg",
    "creator": "Georgi Kalaydzhiev",
    "creatorUrl": "https://unsplash.com/@jorok?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/retro-tv-and-vintage-game-console-with-patterned-wallpaper-ADLkT2JF57c?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "retro tv and vintage game console with patterned wallpaper"
  },
  {
    "id": "6rMK65PSioY",
    "src": "/photos/6rMK65PSioY.jpg",
    "creator": "Jeremy Hynes",
    "creatorUrl": "https://unsplash.com/@hynesight?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/a-glowing-full-moon-in-a-dark-starry-night-sky-6rMK65PSioY?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "a glowing full moon in a dark starry night sky"
  },
  {
    "id": "TkEBaFrYJ_g",
    "src": "/photos/TkEBaFrYJ_g.jpg",
    "creator": "Kay",
    "creatorUrl": "https://unsplash.com/@kewal?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/a-picture-of-the-sydney-opera-house-taken-from-across-the-water-TkEBaFrYJ_g?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "a picture of the sydney opera house taken from across the water"
  },
  {
    "id": "K4mSJ7kc0As",
    "src": "/photos/K4mSJ7kc0As.jpg",
    "creator": "charlesdeluvio",
    "creatorUrl": "https://unsplash.com/@charlesdeluvio?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/black-dog-wearing-blue-denim-collar-K4mSJ7kc0As?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "black dog wearing blue denim collar"
  },
  {
    "id": "h7oZAHnS9_E",
    "src": "/photos/h7oZAHnS9_E.jpg",
    "creator": "Bruce Galpin",
    "creatorUrl": "https://unsplash.com/@star2dev?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/fawn-pug-jumping-on-water-h7oZAHnS9_E?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "fawn pug jumping on water"
  },
  {
    "id": "pOUA8Xay514",
    "src": "/photos/pOUA8Xay514.jpg",
    "creator": "charlesdeluvio",
    "creatorUrl": "https://unsplash.com/@charlesdeluvio?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/adult-black-pug-pOUA8Xay514?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "adult black pug"
  },
  {
    "id": "aPvB8KMIh5w",
    "src": "/photos/aPvB8KMIh5w.jpg",
    "creator": "Nick van der Vegt",
    "creatorUrl": "https://unsplash.com/@nick_vandervegt?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/golden-retriever-puppy-lying-on-floor-aPvB8KMIh5w?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "golden retriever puppy lying on floor"
  },
  {
    "id": "x15GAQNepcQ",
    "src": "/photos/x15GAQNepcQ.jpg",
    "creator": "Liam Edwards",
    "creatorUrl": "https://unsplash.com/@liamedwards?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/people-holding-a-signage-during-daytime-x15GAQNepcQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "people holding a signage during daytime"
  },
  {
    "id": "Hhd-KHf0vpc",
    "src": "/photos/Hhd-KHf0vpc.jpg",
    "creator": "Emanuel Haas",
    "creatorUrl": "https://unsplash.com/@dermanuskript?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/duckling-walking-on-a-rocky-beach-at-sunset-Hhd-KHf0vpc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "duckling walking on a rocky beach at sunset"
  },
  {
    "id": "rKg5T40UlQ4",
    "src": "/photos/rKg5T40UlQ4.jpg",
    "creator": "Rafael Peier",
    "creatorUrl": "https://unsplash.com/@rafaelpeier?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/rocky-mountain-peaks-illuminated-by-golden-sunset-light-rKg5T40UlQ4?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "rocky mountain peaks illuminated by golden sunset light"
  },
  {
    "id": "W7vQRTiuzs0",
    "src": "/photos/W7vQRTiuzs0.jpg",
    "creator": "Marek Piwnicki",
    "creatorUrl": "https://unsplash.com/@marekpiwnicki?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/two-snow-monkeys-on-rocky-mountain-terrain-at-sunrise-W7vQRTiuzs0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "two snow monkeys on rocky mountain terrain at sunrise"
  },
  {
    "id": "Y4VMzlU2OqQ",
    "src": "/photos/Y4VMzlU2OqQ.jpg",
    "creator": "Alexander Mass",
    "creatorUrl": "https://unsplash.com/@alexandermassph?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/two-brown-horses-with-white-faces-in-a-field-Y4VMzlU2OqQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "two brown horses with white faces in a field"
  },
  {
    "id": "yMSecCHsIBc",
    "src": "/photos/yMSecCHsIBc.jpg",
    "creator": "Raoul Droog",
    "creatorUrl": "https://unsplash.com/@raouldroog?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/russian-blue-cat-wearing-yellow-sunglasses-yMSecCHsIBc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "russian blue cat wearing yellow sunglasses"
  },
  {
    "id": "DwkgUqRcHrA",
    "src": "/photos/DwkgUqRcHrA.jpg",
    "creator": "Esteban Chinchilla",
    "creatorUrl": "https://unsplash.com/@esteban__chinchilla?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/white-and-brown-long-fur-cat-DwkgUqRcHrA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "white and brown long fur cat"
  },
  {
    "id": "mnguWkieTd8",
    "src": "/photos/mnguWkieTd8.jpg",
    "creator": "Ahmed Sanie",
    "creatorUrl": "https://unsplash.com/@asanie?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/orange-tabby-cat-sleeping-on-brown-wooden-log-mnguWkieTd8?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "orange tabby cat sleeping on brown wooden log"
  },
  {
    "id": "pfkzBUh4KyA",
    "src": "/photos/pfkzBUh4KyA.jpg",
    "creator": "Martin Sanchez",
    "creatorUrl": "https://unsplash.com/@zekedrone?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/yellow-train-on-rail-tracks-during-daytime-pfkzBUh4KyA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "yellow train on rail tracks during daytime"
  },
  {
    "id": "p69o_a7XqDM",
    "src": "/photos/p69o_a7XqDM.jpg",
    "creator": "Casey Horner",
    "creatorUrl": "https://unsplash.com/@mischievous_penguins?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/gray-and-red-train-running-on-rail-in-between-trees-at-daytime-p69o_a7XqDM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "gray and red train running on rail in between trees at daytime"
  },
  {
    "id": "MwrpaS_6f2U",
    "src": "/photos/MwrpaS_6f2U.jpg",
    "creator": "Francisco Andreotti",
    "creatorUrl": "https://unsplash.com/@frandreotti?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/brown-crt-tv-on-brown-wooden-table-MwrpaS_6f2U?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "brown crt tv on brown wooden table"
  },
  {
    "id": "vOX4XxHo3WI",
    "src": "/photos/vOX4XxHo3WI.jpg",
    "creator": "Ana Curcan",
    "creatorUrl": "https://unsplash.com/@annaacurcan?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/adult-hands-gently-hold-tiny-baby-feet-vOX4XxHo3WI?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "adult hands gently hold tiny baby feet"
  },
  {
    "id": "h_5r08z6E1A",
    "src": "/photos/h_5r08z6E1A.jpg",
    "creator": "Nikita Pishchugin",
    "creatorUrl": "https://unsplash.com/@nikita_pishchugin?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/senior-man-with-walking-stick-on-paris-street-h_5r08z6E1A?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "senior man with walking stick on paris street"
  },
  {
    "id": "oJFTNoQ1q9k",
    "src": "/photos/oJFTNoQ1q9k.jpg",
    "creator": "Pawel Nolbert",
    "creatorUrl": "https://unsplash.com/@hellocolor?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/coca-cola-sign-on-a-building-in-japan-oJFTNoQ1q9k?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "coca cola sign on a building in japan"
  },
  {
    "id": "Ukzgoe_Lwqg",
    "src": "/photos/Ukzgoe_Lwqg.jpg",
    "creator": "Marcus Lenk",
    "creatorUrl": "https://unsplash.com/@marcuslenk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/white-grid-buildings-featuring-diagonal-rainbow-stripes-against-blue-sky-Ukzgoe_Lwqg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "white grid buildings featuring diagonal rainbow stripes against blue sky"
  },
  {
    "id": "YNiXuanD2iY",
    "src": "/photos/YNiXuanD2iY.jpg",
    "creator": "AlaDin Habboubi",
    "creatorUrl": "https://unsplash.com/@aladinhb?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/grand-white-mosque-domes-with-golden-spires-at-dawn-YNiXuanD2iY?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "grand white mosque domes with golden spires at dawn"
  },
  {
    "id": "KWcQ6_dk_OM",
    "src": "/photos/KWcQ6_dk_OM.jpg",
    "creator": "Iwona Castiello d'Antonio",
    "creatorUrl": "https://unsplash.com/@aquadrata?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/city-skyline-during-day-time-KWcQ6_dk_OM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "city skyline during day time"
  },
  {
    "id": "UP22zkjJGZo",
    "src": "/photos/UP22zkjJGZo.jpg",
    "creator": "Tomáš Nožina",
    "creatorUrl": "https://unsplash.com/@tomasnozina?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/people-walking-near-church-during-daytime-UP22zkjJGZo?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "people walking near church during daytime"
  },
  {
    "id": "uoBCga1fNwU",
    "src": "/photos/uoBCga1fNwU.jpg",
    "creator": "Pourya Gohari",
    "creatorUrl": "https://unsplash.com/@_pourya_?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/a-very-tall-building-with-statues-on-its-sides-uoBCga1fNwU?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "a very tall building with statues on its sides"
  },
  {
    "id": "DZqCe7lDwEo",
    "src": "/photos/DZqCe7lDwEo.jpg",
    "creator": "Daniel Seßler",
    "creatorUrl": "https://unsplash.com/@danielsessler?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/snow-cape-mountain-DZqCe7lDwEo?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "snow cape mountain"
  },
  {
    "id": "XYOnEOawQbk",
    "src": "/photos/XYOnEOawQbk.jpg",
    "creator": "zash_ capturing___",
    "creatorUrl": "https://unsplash.com/@zash_capturing___?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "unsplashUrl": "https://unsplash.com/photos/brightly-colored-self-storage-building-with-four-doors-XYOnEOawQbk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
    "alt": "brightly colored self storage building with four doors"
  }
];
